#lang racket/base
(require rackunit racket/list racket/string racket/file "../data/series.rkt" "../data/logstore.rkt" "../data/preset.rkt" "../engine/config.rkt")
;; series roundtrip with wraparound
(define s (make-series 4))
(for ([i (in-range 10)]) (series-push! s i (* i i)))
(check-equal? (series-length s) 4)
(define snap (series-snapshot s))
(check-equal? (map car snap) (list 6 7 8 9))
(check-equal? (map cdr snap) (list 36 49 64 81))
(check-equal? (car (series-last s)) 9)
;; downsample
(check <= (length (series-snapshot s 2)) 2)
(series-clear! s)
(check-equal? (series-length s) 0)
(check-equal? (series-last s) #f)
;; logstore: newest first + filters
(define lg (make-logstore 100))
(log-add! lg (quote engine) (quote info) "started")
(log-add! lg (quote ptp4l) (quote error) "port 1: FAULTY")
(log-add! lg (quote engine) (quote warn) "restart")
(define all (log-snapshot lg))
(check-equal? (length all) 3)
(check-equal? (list-ref (first all) 3) "restart")
(check-equal? (length (log-snapshot lg #:level "error")) 1)
(check-equal? (length (log-snapshot lg #:source "engine")) 2)
(check-equal? (length (log-snapshot lg #:search "faulty")) 1)
(check-true (string-contains? (log->text all) "[ptp4l] [ERROR] port 1: FAULTY"))
(log-clear! lg)
(check-equal? (log-count lg) 0)
;; presets: save/load/delete roundtrip in a temp dir
(parameterize ([presets-dir (make-temporary-file "presets-~a" (quote directory))])
  (check-equal? (preset-names) (list))
  (preset-save "场景A-GM" (quote grandmaster) (default-params-for-role (quote grandmaster)) "enp3s0")
  (preset-save "场景B" (quote slave) (default-params-for-role (quote slave)) "eth0")
  (check-equal? (length (preset-names)) 2)
  (define p (preset-load "场景A-GM"))
  (check-true (hash? p))
  (check-equal? (hash-ref p (quote role)) "grandmaster")
  (check-equal? (hash-ref p (quote iface)) "enp3s0")
  (check-equal? (gptp-params-priority1 (hash-ref p (quote params))) 0)
  (check-equal? (preset-delete "场景A-GM") #t)
  (check-equal? (length (preset-names)) 1))
